import os

anton_death_sound_path = os.path.join('static', 'anton.mp3')
anton_path = os.path.join('static', 'ant.png')
armando_path = os.path.join('static', 'arm.png')
cloud_path = os.path.join("static", "cloud1_transparent_30.png")
cow_path = os.path.join('static', 'cow.png')
david2_death_sound_path = os.path.join('static', 'david.mp3')
david2_path = os.path.join('static', 'david2.png')
david_path = os.path.join('static', 'david.png')
friendly_fire_sound_path = os.path.join('static', 'friendly.mp3')
jc_death_sound_path = os.path.join('static', 'jc.mp3')
jc_path = os.path.join('static', 'jcr.png')
laser_sound_path = os.path.join("static", "laser.mp3")
opponent_path = None
point_gain_sound_path = os.path.join('static', 'point.wav')
point_loss_sound_path = os.path.join('static', 'hurt.wav')
ranger_path = os.path.join("static", "rangership_50.png")
ricky_death_sound_path = os.path.join('static', 'ricky_oof.mp3')
ricky_path = os.path.join('static', 'ricky.png')
sky_path = os.path.join("static", "background2.jpeg")
wrong_answer_sound_path = os.path.join('static', 'wrong_answer.mp3')
